In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("diabetes.csv")

In [4]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

## Part 1

In [5]:
df.sort_values(by="Age")

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
255,1,113,64,35,0,33.6,0.543,21,1
60,2,84,0,0,0,0.0,0.304,21,0
102,0,125,96,0,0,22.5,0.262,21,0
182,1,0,74,20,23,27.7,0.299,21,0
623,0,94,70,27,115,43.5,0.347,21,0
...,...,...,...,...,...,...,...,...,...
123,5,132,80,0,0,26.8,0.186,69,0
684,5,136,82,0,0,0.0,0.640,69,0
666,4,145,82,18,0,32.5,0.235,70,1
453,2,119,0,0,0,19.6,0.832,72,0
459,9,134,74,33,60,25.9,0.460,81,0

In [6]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.sort_values("Age")

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
255,1,113,64,35,0,33.6,0.543,21,1
60,2,84,0,0,0,0.0,0.304,21,0
102,0,125,96,0,0,22.5,0.262,21,0
182,1,0,74,20,23,27.7,0.299,21,0
623,0,94,70,27,115,43.5,0.347,21,0
...,...,...,...,...,...,...,...,...,...
123,5,132,80,0,0,26.8,0.186,69,0
684,5,136,82,0,0,0.0,0.640,69,0
666,4,145,82,18,0,32.5,0.235,70,1
453,2,119,0,0,0,19.6,0.832,72,0
459,9,134,74,33,60,25.9,0.460,81,0

In [8]:
df.sort_values(by="BMI",ascending=False)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
177,0,129,110,46,130,67.1,0.319,26,1
445,0,180,78,63,14,59.4,2.420,25,1
673,3,123,100,35,240,57.3,0.880,22,0
125,1,88,30,42,99,55.0,0.496,26,1
120,0,162,76,56,100,53.2,0.759,25,1
...,...,...,...,...,...,...,...,...,...
81,2,74,0,0,0,0.0,0.102,22,0
371,0,118,64,23,89,0.0,1.731,21,0
522,6,114,0,0,0,0.0,0.189,26,0
49,7,105,0,0,0,0.0,0.305,24,0
706,10,115,0,0,0,0.0,0.261,30,1

## Part 2

In [9]:
older = df["Age"] > 60

In [10]:
older_df=df.loc[older]

In [11]:
older_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
115,4,146,92,0,0,31.2,0.539,61,1
123,5,132,80,0,0,26.8,0.186,69,0
129,0,105,84,0,0,27.9,0.741,62,1
148,5,147,78,0,0,33.7,0.218,65,0
221,2,158,90,0,0,31.6,0.805,66,1
223,7,142,60,33,190,28.8,0.687,61,0
263,3,142,80,15,0,32.4,0.200,63,0
294,0,161,50,0,0,21.9,0.254,65,0
361,5,158,70,0,0,29.8,0.207,63,0
362,5,103,108,37,0,39.2,0.305,65,0
363,4,146,78,0,0,38.5,0.520,67,1
453,2,119,0,0,0,19.6,0.832,72,0
456,1,135,54,0,0,26.7,0.687,62,0
459,9,134,74,33,60,25.9,0.460,81,0
479,4,132,86,31,0,28.0,0.419,63,0
489,8,194,80,0,0,26.1,0.551,67,0
495,6,166,74,0,0,26.6,0.304,66,0
509,8,120,78,0,0,25.0,0.409,64,0
537,0,57,60,0,0,21.7,0.735,67,0
552,6,114,88,0,0,27.8,0.247,66,0
579,2,197,70,99,0,34.7,0.575,62,1
582,12,121,78,17,0,26.5,0.259,62,0
666,4,145,82,18,0,32.5,0.235,70,1
674,8,91,82,0,0,35.6,0.587,68,0
684,5,136,82,0,0,0.0,0.640,69,0
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

In [12]:
len(older_df)

27

In [13]:
outcome_1 = df.loc[df["Outcome"]== 1]

In [14]:
outcome_1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [15]:
outcome_0 = df.loc[df["Outcome"] == 0]

In [16]:
outcome_0

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
10,4,110,92,0,0,37.6,0.191,30,0
...,...,...,...,...,...,...,...,...,...
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
767,1,93,70,31,0,30.4,0.315,23,0

In [17]:
insulin_0 = df.loc[df["Insulin"] == 0]

In [18]:
insulin_0

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
...,...,...,...,...,...,...,...,...,...
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
764,2,122,70,27,0,36.8,0.340,27,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [19]:
high_glucose = df.loc[df["Glucose"] > 180]

In [20]:
high_glucose

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
2,8,183,64,0,0,23.3,0.672,32,1
8,2,197,70,45,543,30.5,0.158,53,1
13,1,189,60,23,846,30.1,0.398,59,1
22,7,196,90,0,0,39.8,0.451,41,1
56,7,187,68,39,304,37.7,0.254,41,1
154,8,188,78,0,0,47.9,0.137,43,1
185,7,194,68,28,0,35.9,0.745,41,1
186,8,181,68,36,495,30.1,0.615,60,1
206,8,196,76,29,280,37.5,0.605,57,1
209,7,184,84,33,0,35.5,0.355,41,1
228,4,197,70,39,744,36.7,2.329,31,0
236,7,181,84,21,192,35.9,0.586,51,1
245,9,184,85,15,0,30.0,1.213,49,1
258,1,193,50,16,375,25.9,0.655,24,0
260,3,191,68,15,130,30.9,0.299,34,0
317,3,182,74,0,0,30.5,0.345,29,1
319,6,194,78,0,0,23.5,0.129,59,1
359,1,196,76,36,249,36.5,0.875,29,1
360,5,189,64,33,325,31.2,0.583,29,1
399,3,193,70,31,0,34.9,0.241,25,1
408,8,197,74,0,0,25.9,1.191,39,1
425,4,184,78,39,277,37.0,0.264,31,1
427,1,181,64,30,180,34.1,0.328,38,1
440,0,189,104,25,0,34.3,0.435,41,1
489,8,194,80,0,0,26.1,0.551,67,0
498,7,195,70,33,145,25.1,0.163,55,1
545,8,186,90,35,225,34.5,0.423,37,1
546,5,187,76,27,207,43.6,1.034,53,1
549,4,189,110,31,0,28.5,0.680,37,0
561,0,198,66,32,274,41.3,0.502,28,1
579,2,197,70,99,0,34.7,0.575,62,1
595,0,188,82,14,185,32.0,0.682,22,1
604,4,183,0,0,0,28.4,0.212,36,1
606,1,181,78,42,293,40.0,1.258,22,1
622,6,183,94,0,0,40.8,1.461,45,0
661,1,199,76,43,0,42.9,1.394,22,1
675,6,195,70,0,0,30.9,0.328,31,1
715,7,187,50,33,392,33.9,0.826,34,1
748,3,187,70,22,200,36.4,0.408,36,1
753,0,181,88,44,510,43.3,0.222,26,1
759,6,190,92,0,0,35.5,0.278,66,1

## Part 3

In [21]:
high_risk_young_patient = df.loc[(df["Age"] < 30) & (df["BMI"] > 35)]

In [22]:
high_risk_young_patient

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
7,10,115,0,0,0,35.3,0.134,29,0
20,3,126,88,41,235,39.3,0.704,27,0
38,2,90,68,42,0,38.2,0.503,27,1
45,0,180,66,39,0,42.0,1.893,25,1
59,0,105,64,41,142,41.5,0.173,22,0
...,...,...,...,...,...,...,...,...,...
746,1,147,94,41,0,49.3,0.358,27,1
751,1,121,78,39,74,39.0,0.261,28,0
753,0,181,88,44,510,43.3,0.222,26,1
758,1,106,76,0,0,37.5,0.197,26,0
764,2,122,70,27,0,36.8,0.340,27,0

In [25]:
spefific_health_markers = df.loc[(df["BloodPressure"]> 90) | (df["Glucose"] > 160)]

In [26]:
spefific_health_markers

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
2,8,183,64,0,0,23.3,0.672,32,1
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
...,...,...,...,...,...,...,...,...,...
748,3,187,70,22,200,36.4,0.408,36,1
749,6,162,62,0,0,24.3,0.178,50,1
753,0,181,88,44,510,43.3,0.222,26,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1

In [27]:
healthy_and_young = high_risk_young_patient = df.loc[(df["Age"] < 25) & (df["Outcome"] == 0)]

In [28]:
healthy_and_young

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
3,1,89,66,23,94,28.1,0.167,21,0
27,1,97,66,15,140,23.2,0.487,22,0
32,3,88,58,11,54,24.8,0.267,22,0
47,2,71,70,27,0,28.0,0.586,22,0
49,7,105,0,0,0,0.0,0.305,24,0
...,...,...,...,...,...,...,...,...,...
736,0,126,86,27,120,27.4,0.515,21,0
738,2,99,60,17,160,36.6,0.453,21,0
742,1,109,58,18,116,28.5,0.219,22,0
760,2,88,58,26,16,28.4,0.766,22,0
767,1,93,70,31,0,30.4,0.315,23,0

In [29]:
normal_bmi = df.loc[(df["BMI"] < 29.9) & (df["BMI"] > 25)]

In [30]:
normal_bmi

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
12,10,139,80,0,0,27.1,1.441,57,0
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
736,0,126,86,27,120,27.4,0.515,21,0
742,1,109,58,18,116,28.5,0.219,22,0
752,3,108,62,24,0,26.0,0.223,25,0
760,2,88,58,26,16,28.4,0.766,22,0
765,5,121,72,23,112,26.2,0.245,30,0

In [31]:
null_value_investigate = df.loc[(df["BloodPressure"] > 0) & (df["BMI"] > 0) & (df["Glucose"] > 0)]

In [32]:
null_value_investigate

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## Part 4

In [33]:
top_diabetic = df.loc[df["Outcome"] == 1]

In [36]:
top_diabetic.sort_values(by="Glucose",ascending=False, inplace=True)

C:\Users\ram\AppData\Local\Temp\ipykernel_14028\388795565.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_diabetic.sort_values(by="Glucose",ascending=False, inplace=True)

In [37]:
top_diabetic.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
661,1,199,76,43,0,42.9,1.394,22,1
561,0,198,66,32,274,41.3,0.502,28,1
579,2,197,70,99,0,34.7,0.575,62,1
408,8,197,74,0,0,25.9,1.191,39,1
8,2,197,70,45,543,30.5,0.158,53,1
22,7,196,90,0,0,39.8,0.451,41,1
359,1,196,76,36,249,36.5,0.875,29,1
206,8,196,76,29,280,37.5,0.605,57,1
675,6,195,70,0,0,30.9,0.328,31,1
498,7,195,70,33,145,25.1,0.163,55,1

In [38]:
youngest_patients_with_high_insulin = df.loc[df["Insulin"] > 200]

In [39]:
youngest_patients_with_high_insulin.sort_values(by=["Age"],inplace=True)

C:\Users\ram\AppData\Local\Temp\ipykernel_14028\117319355.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youngest_patients_with_high_insulin.sort_values(by=["Age"],inplace=True)

In [42]:
youngest_patients_with_high_insulin.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
713,0,134,58,20,291,26.4,0.352,21,0
486,1,139,62,41,480,40.7,0.536,21,0
220,0,177,60,29,478,34.6,1.072,21,1
511,0,139,62,17,210,22.1,0.207,21,0
392,1,131,64,14,415,23.7,0.389,21,0

In [43]:
pregnancy_and_pedigree = df.loc[df["Pregnancies"] > 5].sort_values(by="DiabetesPedigreeFunction",ascending=False)

In [44]:
pregnancy_and_pedigree

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
330,8,118,72,19,0,23.1,1.476,46,0
622,6,183,94,0,0,40.8,1.461,45,0
12,10,139,80,0,0,27.1,1.441,57,0
259,11,155,76,28,150,33.3,1.353,51,1
243,6,119,50,22,176,27.1,1.318,33,1
...,...,...,...,...,...,...,...,...,...
329,6,105,70,32,68,30.8,0.122,37,0
560,6,125,76,0,0,33.8,0.121,54,1
146,9,57,80,37,0,32.8,0.096,41,0
567,6,92,62,32,126,32.0,0.085,46,0
180,6,87,80,0,0,23.2,0.084,32,0

## Part 5

In [45]:
high_risk_profile = df.loc[ (df["Age"] > 45) & (df["BMI"] > 30) & (df["Glucose"] > 150)]

In [ ]:
high_risk_profile.shape[0] # len(high_risk_profile)

23

In [64]:
new_data = df["Pregnancies"].isin([1,3,5]) # df.isin({"Pregnancies":[1,3,5]})

In [65]:
df[new_data]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
13,1,189,60,23,846,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
758,1,106,76,0,0,37.5,0.197,26,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

# Completed ðŸŽ‰